\c gevents;
delete from venues where id > 0;
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Streamlined fresh-thinking matrices', 36, '63 Logan Pass', '4', 'Santa Ana', 'CA', '92725');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Up-sized fresh-thinking collaboration', 27, '10274 Tomscot Place', '784', 'Atlanta', 'GA', '30375');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Devolved fault-tolerant concept', 98, '7755 Swallow Parkway', '122', 'El Paso', 'TX', '79999');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Sharable analyzing function', 46, '5 Ridgeview Park', '35168', 'Kansas City', 'MO', '64101');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('User-friendly solution-oriented function', 25, '48847 Riverside Terrace', '11517', 'Newport News', 'VA', '23612');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Horizontal 6th generation strategy', 34, '2 Buena Vista Parkway', '45', 'Hartford', 'CT', '06152');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Reverse-engineered upward-trending knowledge user', 67, '0 East Circle', '679', 'Des Moines', 'IA', '50335');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Progressive 4th generation support', 43, '72 Pond Plaza', '1642', 'Santa Fe', 'NM', '87505');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Multi-channelled hybrid concept', 40, '3898 Warbler Trail', '218', 'Kent', 'WA', '98042');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Persevering bi-directional paradigm', 78, '894 Morningstar Trail', '904', 'Birmingham', 'AL', '35225');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Profit-focused exuding open system', 46, '4702 Vera Parkway', '38', 'Charleston', 'WV', '25356');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Virtual well-modulated workforce', 82, '96559 Orin Crossing', '52007', 'Minneapolis', 'MN', '55412');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Cross-platform motivating access', 100, '7155 Larry Terrace', '9825', 'Norman', 'OK', '73071');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Diverse bottom-line access', 46, '4453 Bellgrove Junction', '769', 'Albuquerque', 'NM', '87195');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Right-sized zero tolerance intranet', 58, '7443 Homewood Place', '21682', 'Fort Lauderdale', 'FL', '33305');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Down-sized bi-directional structure', 42, '00276 Heffernan Street', '0', 'Salt Lake City', 'UT', '84120');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Digitized clear-thinking intranet', 76, '3109 Almo Junction', '72', 'Utica', 'NY', '13505');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Programmable 3rd generation extranet', 84, '5298 Dryden Junction', '5', 'Spokane', 'WA', '99205');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Profound analyzing website', 68, '0799 Grim Junction', '8', 'Yakima', 'WA', '98907');
insert into venues (name, capacity, line_1, line_2, city, state, zip) values ('Open-architected tangible analyzer', 100, '2 Bobwhite Plaza', '4891', 'Boston', 'MA', '02119');
